import mongoose, { Schema, Types, type Document, type Model } from "mongoose";
import type { Currency, LotStatus } from "@sadiyakargo/shared";

interface PhotoRef {
  _id: Types.ObjectId;
  storageKey: string;
  mimeType: string;
  sizeBytes: number;
  width?: number;
  height?: number;
  uploadedAt: Date;
}

interface UnitPrice {
  amount: number;
  currency: Currency;
}

export interface LotDoc extends Document {
  _id: Types.ObjectId;
  orgId: Types.ObjectId;
  senderId: Types.ObjectId;
  label: string;
  qtyIn: number;
  qtyAvailable: number;
  unitPrice: UnitPrice | null;
  receivedAt: Date;
  notes: string;
  status: LotStatus;
  photos: PhotoRef[];
  deletedAt?: Date | null;
  createdAt: Date;
  updatedAt: Date;
  toClient(): {
    id: string;
    senderId: string;
    label: string;
    qtyIn: number;
    qtyAvailable: number;
    unitPrice: UnitPrice | null;
    receivedAt: string;
    notes: string;
    status: LotStatus;
    photos: {
      id: string;
      mimeType: string;
      sizeBytes: number;
      width?: number;
      height?: number;
      uploadedAt: string;
    }[];
    createdAt: string;
    updatedAt: string;
  };
}

const lotSchema = new Schema<LotDoc>(
  {
    orgId: { type: Schema.Types.ObjectId, required: true, index: true },
    senderId: { type: Schema.Types.ObjectId, ref: "Sender", required: true },
    label: { type: String, default: "" },
    qtyIn: { type: Number, required: true, min: 1 },
    qtyAvailable: { type: Number, required: true, min: 0 },
    unitPrice: {
      type: new Schema(
        {
          amount: { type: Number, required: true, min: 0 },
          currency: { type: String, required: true, enum: ["USD", "UZS", "TRY"] },
        },
        { _id: false }
      ),
      default: null,
    },
    receivedAt: { type: Date, required: true, default: () => new Date() },
    notes: { type: String, default: "" },
    status: {
      type: String,
      enum: ["in_stock", "partially_shipped", "fully_shipped", "withdrawn"],
      default: "in_stock",
    },
    photos: {
      // _id is auto-generated by Mongoose (ObjectId) and surfaced as `id`
      // in toClient, so the API can address individual photos in
      // GET/DELETE /lots/:id/photos/:photoId.
      type: [
        new Schema({
          storageKey: { type: String, required: true },
          mimeType: { type: String, required: true },
          sizeBytes: { type: Number, required: true },
          width: Number,
          height: Number,
          uploadedAt: { type: Date, default: () => new Date() },
        }),
      ],
      default: [],
    },
    deletedAt: { type: Date, default: null },
  },
  { timestamps: true }
);

lotSchema.index({ orgId: 1, senderId: 1, status: 1 });
lotSchema.index({ orgId: 1, receivedAt: -1 });

lotSchema.methods.toClient = function toClient() {
  // unitPrice is a Mongoose subdocument when present — return a plain POJO
  // so audit middleware / JSON.stringify don't walk into $__parent cycles.
  const up = this.unitPrice;
  const unitPrice =
    up && typeof up === "object"
      ? { amount: up.amount, currency: up.currency as UnitPrice["currency"] }
      : null;
  return {
    id: this._id.toString(),
    senderId: this.senderId.toString(),
    label: this.label ?? "",
    qtyIn: this.qtyIn,
    qtyAvailable: this.qtyAvailable,
    unitPrice,
    receivedAt: this.receivedAt.toISOString(),
    notes: this.notes,
    status: this.status,
    photos: this.photos.map((p: PhotoRef) => ({
      // Defensive: photos[] sub-schema dropped `{_id:false}`, so Mongoose
      // mints `_id` for new docs — but any pre-existing element written
      // before that change lacks `_id` entirely. Synthesise a fresh one
      // rather than throwing on `.toString()`; the consumer just sees a
      // stable id within this response.
      id: p._id ? p._id.toString() : new Types.ObjectId().toString(),
      // `storageKey` is intentionally NOT exposed — clients fetch through
      // `GET /lots/:id/photos/:photoId` which returns a presigned URL, so
      // the S3 key layout stays internal.
      mimeType: p.mimeType,
      sizeBytes: p.sizeBytes,
      ...(p.width !== undefined ? { width: p.width } : {}),
      ...(p.height !== undefined ? { height: p.height } : {}),
      uploadedAt: p.uploadedAt.toISOString(),
    })),
    createdAt: this.createdAt.toISOString(),
    updatedAt: this.updatedAt.toISOString(),
  };
};

export const InboundLot: Model<LotDoc> =
  (mongoose.models.InboundLot as Model<LotDoc>) || mongoose.model<LotDoc>("InboundLot", lotSchema);
